schema = """-- MySQL Script generated by MySQL Workbench
-- Fri Aug  1 20:21:59 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema meu_projeto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema meu_projeto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `meu_projeto` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `meu_projeto` ;

-- -----------------------------------------------------
-- Table `meu_projeto`.`alembic_version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meu_projeto`.`alembic_version` (
  `version_num` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`version_num`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `meu_projeto`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meu_projeto`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `data_cadastro` DATETIME NOT NULL,
  `data_atualizacao` DATETIME NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ix_categorias_nome` (`nome` ASC) VISIBLE,
  INDEX `idx_categoria_ativo` (`ativo` ASC) VISIBLE,
  INDEX `ix_categorias_id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `meu_projeto`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meu_projeto`.`empresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(14) NOT NULL,
  `razao_social` VARCHAR(128) NOT NULL,
  `nome_fantasia` VARCHAR(64) NULL DEFAULT NULL,
  `numero_contato` VARCHAR(9) NULL DEFAULT NULL,
  `email_contato` VARCHAR(64) NULL DEFAULT NULL,
  `website` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `meu_projeto`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meu_projeto`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `endereco` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `tipo` ENUM('CLIENTE', 'FUNCIONARIO', 'ADMINISTRADOR') NOT NULL,
  `matricula` VARCHAR(20) NULL DEFAULT NULL,
  `data_cadastro` DATETIME NOT NULL,
  `data_atualizacao` DATETIME NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `limite_emprestimos` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ix_usuarios_cpf` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `ix_usuarios_email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `ix_usuarios_matricula` (`matricula` ASC) VISIBLE,
  INDEX `idx_usuario_ativo` (`ativo` ASC, `tipo` ASC) VISIBLE,
  INDEX `ix_usuarios_id` (`id` ASC) VISIBLE,
  INDEX `ix_usuarios_tipo` (`tipo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `meu_projeto`.`livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meu_projeto`.`livros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(200) NOT NULL,
  `autor` VARCHAR(100) NOT NULL,
  `isbn` VARCHAR(13) NOT NULL,
  `editora` VARCHAR(100) NOT NULL,
  `ano_publicacao` INT NOT NULL,
  `edicao` VARCHAR(20) NULL DEFAULT NULL,
  `quantidade_total` INT NOT NULL,
  `quantidade_disponivel` INT NOT NULL,
  `categoria_id` INT NOT NULL,
  `localizacao` VARCHAR(50) NOT NULL,
  `data_cadastro` DATETIME NOT NULL,
  `data_atualizacao` DATETIME NOT NULL,
  `sinopse` TEXT NULL DEFAULT NULL,
  `capa_url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ix_livros_isbn` (`isbn` ASC) VISIBLE,
  INDEX `idx_livro_disponivel` (`quantidade_disponivel` ASC, `categoria_id` ASC) VISIBLE,
  INDEX `ix_livros_autor` (`autor` ASC) VISIBLE,
  INDEX `ix_livros_categoria_id` (`categoria_id` ASC) VISIBLE,
  INDEX `ix_livros_id` (`id` ASC) VISIBLE,
  INDEX `ix_livros_titulo` (`titulo` ASC) VISIBLE,
  CONSTRAINT `livros_ibfk_1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `meu_projeto`.`categorias` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `meu_projeto`.`emprestimos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meu_projeto`.`emprestimos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `livro_id` INT NOT NULL,
  `funcionario_id` INT NOT NULL,
  `data_emprestimo` DATETIME NOT NULL,
  `data_devolucao_prevista` DATETIME NOT NULL,
  `data_devolucao_real` DATETIME NULL DEFAULT NULL,
  `status` ENUM('ATIVO', 'DEVOLVIDO', 'ATRASADO', 'PERDIDO') NOT NULL,
  `observacoes` TEXT NULL DEFAULT NULL,
  `dias_emprestimo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_emprestimo_status` (`status` ASC, `data_devolucao_prevista` ASC) VISIBLE,
  INDEX `ix_emprestimos_funcionario_id` (`funcionario_id` ASC) VISIBLE,
  INDEX `ix_emprestimos_id` (`id` ASC) VISIBLE,
  INDEX `ix_emprestimos_livro_id` (`livro_id` ASC) VISIBLE,
  INDEX `ix_emprestimos_status` (`status` ASC) VISIBLE,
  INDEX `ix_emprestimos_usuario_id` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `emprestimos_ibfk_1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `meu_projeto`.`usuarios` (`id`),
  CONSTRAINT `emprestimos_ibfk_2`
    FOREIGN KEY (`livro_id`)
    REFERENCES `meu_projeto`.`livros` (`id`),
  CONSTRAINT `emprestimos_ibfk_3`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `meu_projeto`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `meu_projeto`.`multas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meu_projeto`.`multas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emprestimo_id` INT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `data_geracao` DATETIME NOT NULL,
  `data_pagamento` DATETIME NULL DEFAULT NULL,
  `status` ENUM('PENDENTE', 'PAGO', 'CANCELADA') NOT NULL,
  `motivo` TEXT NOT NULL,
  `dias_atraso` INT NOT NULL,
  `valor_por_dia` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_multa_status` (`status` ASC, `data_geracao` ASC) VISIBLE,
  INDEX `ix_multas_emprestimo_id` (`emprestimo_id` ASC) VISIBLE,
  INDEX `ix_multas_id` (`id` ASC) VISIBLE,
  INDEX `ix_multas_status` (`status` ASC) VISIBLE,
  CONSTRAINT `multas_ibfk_1`
    FOREIGN KEY (`emprestimo_id`)
    REFERENCES `meu_projeto`.`emprestimos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `meu_projeto`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meu_projeto`.`reservas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `livro_id` INT NOT NULL,
  `data_reserva` DATETIME NOT NULL,
  `data_limite` DATETIME NOT NULL,
  `status` ENUM('PENDENTE', 'CONCLUIDA', 'CANCELADA', 'EXPIRADA') NOT NULL,
  `prioridade` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_reserva_status` (`status` ASC, `data_limite` ASC) VISIBLE,
  INDEX `ix_reservas_id` (`id` ASC) VISIBLE,
  INDEX `ix_reservas_livro_id` (`livro_id` ASC) VISIBLE,
  INDEX `ix_reservas_status` (`status` ASC) VISIBLE,
  INDEX `ix_reservas_usuario_id` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `reservas_ibfk_1`
    FOREIGN KEY (`livro_id`)
    REFERENCES `meu_projeto`.`livros` (`id`),
  CONSTRAINT `reservas_ibfk_2`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `meu_projeto`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
"""